version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    networks:
      - influencia
    volumes:
      - ./:/var/www
    ports:
      - '${APP_PORT:-80}:80'
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    networks:
      - influencia
    volumes:
      - ./:/var/www
  
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: db
    hostname: db
    restart: always
    ports:
      - 3306:3306
    networks:
      - influencia
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

networks:
  influencia:
    driver: bridge
volumes:
  mysql_data: